### ISSUE TITLE
Connexion à la Dapp

### ISSUE THREAD

**Issue by mavy77** [AlyraButerin/VotingDapp#1]
**En tant que**  utilisateur (Owner ou voter)
**Je souhaite** me connecter à la Dapp via le plugin metamask
**Afin de** D'avoir accès aux fonctionnalités de la Dapp selon mon Rôle

Règles:
- Si l'utilisateur n'a pas le plugin, l'inviter à télécharger le plugin
-

**Comment by mavy77** [comment]
à completer

**Comment by ibourn** [comment]
géré avec le #26 : context to manage connexion

il restera la partie design à faire
